name: CD

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            zip

      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure CMake
        run: cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: CMake Build
        run: cmake --build build --parallel

      - name: Strip binaries
        run: |
          strip --strip-all build/run_hidden.exe
          strip --strip-all build/run_hidden_wait.exe

      - name: Package artifacts
        run: |
          mkdir release
          cp build/run_hidden.exe build/run_hidden_wait.exe release/
          zip -r run_hidden-${{ github.ref_name }}.zip release/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: run_hidden-${{ github.ref_name }}
          path: run_hidden-${{ github.ref_name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/**/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
