name: CI

on:
  push:
    branches: [ main ]
    paths: &ci_paths
      - 'src/**'
      - 'include/**'
      - 'main.c'
      - 'CMakeLists.txt'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [ windows-latest ]
        cmake_version: [ 3.21.0, latest ]
        c_standard: [ '99', '23' ]

    runs-on: ${{ matrix.os }}

    env:
      SCCACHE_GHA_ENABLED: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake_version }}
        if: matrix.cmake_version != 'latest'

      - name: Echo CMake version
        run: cmake --version

      - name: Configure CMake
        run: >
          cmake . -B build
          -G Ninja
          -DCMAKE_C_STANDARD=${{ matrix.c_standard }}
          -DCMAKE_C_COMPILER_LAUNCHER=sccache

      - name: CMake Build
        run: cmake --build build --parallel
